databases:
  - name: beatboxer-collections-db
    databaseName: beatboxer-collections-db
    user: yusuke
    region: singapore

services:
  - type: web
    name: beatboxer-collection
    env: ruby
    region: singapore
    plan: free
    buildCommand: "bundle install; bundle exec rake assets:precompile;"
    startCommand: "bundle exec rails db:migrate && bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beatboxer-collections-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

